### ISSUE TITLE
when i install react-gantt something was wrong,but my global react version is 15.4.2

### ISSUE THREAD

**Issue by LalaChu** [jamrizzi/react-gantt#3]
error code EPEERINVALID
1722 error peerinvalid The package react@15.5.4 does not satisfy its siblings' peerDependencies requirements!
1722 error peerinvalid Peer react-addons-transition-group@15.5.2 wants react@^15.4.2
1722 error peerinvalid Peer react-dom@15.4.2 wants react@^15.4.2
1722 error peerinvalid Peer react-redux@5.0.3 wants react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0
1722 error peerinvalid Peer recharts@0.22.3 wants react@^0.14.0 || ^15.0.0
1722 error peerinvalid Peer gantt-for-react@0.0.6 wants react@>=0.13.2 || ^0.14 || ^15.0.0
1722 error peerinvalid Peer react-router@3.0.2 wants react@^0.14.0 || ^15.0.0
1722 error peerinvalid Peer react-gantt@1.1.1 wants react@^0.14.0

**Comment by jamrizzi** [comment]
I'm in the process of a major refactor of the codebase. Hopefully, this will end up fixing it.

https://github.com/jamrizzi/react-gantt/tree/jamrizzi/major-refactor

I should have the refactor finished by the end of May.
