### ISSUE TITLE
Not work with react@16.

### ISSUE THREAD

**Issue by ViktorSoroka** [jamrizzi/react-gantt#4]
Dependency *react-window-resize-listener* uses react features which is dropped from react@16 such *React.PropTypes* and *React.createClass* methods.

**Comment by jamrizzi** [comment]
I'm in the process of refactoring the whole project. It should be done by the end of this month.

**Comment by jamrizzi** [comment]
You can see the changes at https://github.com/jamrizzi/react-gantt/tree/jamrizzi/major-refactor.

**Comment by ViktorSoroka** [comment]
Cool. Please do not close it unless you finish then.

**Comment by jamrizzi** [comment]
I won't close the issue until the issue is fixed.

**Comment by jamrizzi** [comment]
I encourage you to check out my new code

You can see the updated demo at https://jamrizzi.github.io/react-gantt/

It's still not finished, but the reactor is at least functional now

**Comment by jamrizzi** [comment]
This is fixed with v2
