### ISSUE TITLE
React-native not supported

### ISSUE THREAD

**Issue by burkaslarry** [jamrizzi/react-gantt#7]
When I follow your works on example and runs, it cause the following error after react-native run-ios

![screenshot 2018-03-23 00 23 53](https://user-images.githubusercontent.com/5709615/37783515-a4320e1e-2e30-11e8-950c-9f1b383573dd.png)

what should  i do ?

**Comment by jamrizzi** [comment]
Correct, this project uses the native DOM for rendering. Mobile apps do not have a native DOM. I am sorry to say that you will need to use a different project for mobile.
